### ISSUE TITLE
Compilation Issues with SecApi TA Library on OP-TEE OS Due to Pthread and Incomplete libc Support

### ISSUE THREAD

**Issue by Hanlin928** [rdkcentral/tasecureapi#110]
Hello,

I've encountered a significant number of compilation issues while trying to build the SecApi TA library for the OP-TEE OS. Specifically, the code within `reference/src/taimpl/src/internal/cipher_store.c` utilizes pthread, which is not supported by OP-TEE OS.

My question is whether pthread is essential within the TA side library? Since OP-TEE also lacks full libc support, similar issues arise in other areas, such as `reference/src/taimpl/src/internal/cenc.c`, which includes `inet.h` and is missing numerous symbols.

Have you encountered these types of issues when compiling for the OP-TEE platform? Could you suggest how to handle such compilation problems? Is it possible to work around these issues by modifying the code outside of the porting layer?

Any guidance or recommendations would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Hanlin.Wang

**Comment by riwoh** [comment]
Hi Hanlin, 

I apologize for the delay in responding.  

1. Regarding the missing symbols from inet.h, many of them are endian-safe operators.  They can also be grabbed from stdlib.h, or you can pull the defines you need from endian.h.  

2. pthread is not essential to the operation of the TA implementation.   While many of the reference implementation design choices were influenced by OPTEE, we did opt for implementing thread safety in the TA in the case of TEE that could support it.  If there is no concern for concurrent access or race conditions in your TA implementation (ie single thread), you can probably ignore those calls.

Richard Woh

**Comment by Hanlin928** [comment]
Hi Richard,

Thank you for your reply. I have made modifications to the inet and pthread parts according to your suggestions. Now, I have encountered issues with time-related libc functions and would like to ask for your advice on the following:

1. In reference/src/taimpl/src/internal/key_store.c and rights.c, the time(NULL) function is called multiple times to obtain the current system time. Since OP-TEE does not support time-related libc functions, my understanding is that I should use the GlobalPlatform (GP) APIs to obtain the system time from the Rich Execution Environment (REE). Could you confirm if my understanding is correct?

2. In reference/src/taimpl/src/internal/typej.c, functions strptime() and timegm() are called. I assume that, similar to the situation with inet, I should implement the missing functions myself, right?

**Comment by riwoh** [comment]
Hi Hanlin, 

1. Yes, you may need to use an OPTEE function such as `TEE_GetREETime` or something like that. 
2. You assume correctly.  We need a function to parse the time, so if you could find an implementation that works in OPTEE that would be good.

**Comment by Hanlin928** [comment]
Thanks your suggestions. Let me close this issue.
