### ISSUE TITLE
Compilation Issues with Google Test on OP-TEE Platform

### ISSUE THREAD

**Issue by Hanlin928** [rdkcentral/tasecureapi#113]
Hello,

We are experiencing compilation issues with Google Test while building the tests located in `reference/src/taimpl/test`. The problem arises because Google Test relies on many C++ features, which are not supported by the OP-TEE platform. For more details, please refer to the following links:
- [OP-TEE Toolchains](https://optee.readthedocs.io/en/latest/building/toolchains.html#id2)
- [OP-TEE FAQ - C++ Libraries](https://optee.readthedocs.io/en/latest/faq/faq.html#q-can-i-use-c-libraries-in-op-tee)

I would like to seek advice on a few points and ultimately resolve the compilation issues mentioned above:

1. Is Google Test necessary within the TEE? Why not control the entire test process through Google Test in the REE instead?
2. What would be the impact of disabling the compilation of Google Test within the TEE? Would the test suite still be executable? What is the approximate test coverage we could expect?

Any suggestions or guidance on how to proceed with these issues would be greatly appreciated.

Thank you for your assistance.

Best regards,
Hanlin.Wang

**Comment by riwoh** [comment]
Hi Hanlin, 

The Google Tests are for us to verify the reference taimpl.  This will obviously not be supported in OPTEE environment. You may need to implement your own TEE unit tests if you need.   Otherwise, you can just rely on the REE side unit tests to evaluate your SecAPI3 implementation.

Richard Woh

**Comment by Hanlin928** [comment]
Hi Richard,

Thank for your suggestion.
We will disable the taimpltest compiling by modifying the cmake scripts and reply on the REE side unit tests for SecAPI3 verification.
One more question is that is there plan to add an option to disable taimpltest compling?

**Comment by riwoh** [comment]
Not in the reference implementation.  Anyone can just comment it out from the CMake file though.
